apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service-pod
          image: kamalv007/social-post-service:v2
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8082
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8082"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pulse-secrets
                  key: post-service-database-url
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: pulse-shared-config
                  key: REDIS_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pulse-shared-config
                  key: USER_SERVICE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pulse-shared-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
