// Package repository implements the data-access layer for users using raw
// database/sql. Every query is parameterized to prevent SQL injection.
// No ORM is used — this keeps the dependency surface tiny and makes queries
// explicit and auditable.
package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/pulse-social/user-service/internal/model"
)

// UserRepository provides CRUD operations for the users table.
type UserRepository struct {
	db *sql.DB
}

// NewUserRepository creates a new repository backed by the given database handle.
func NewUserRepository(db *sql.DB) *UserRepository {
	return &UserRepository{db: db}
}

// Create inserts a new user and returns the fully populated User (with
// server-generated ID and timestamps). The UUID is generated by PostgreSQL
// via gen_random_uuid(), not by the application.
func (r *UserRepository) Create(ctx context.Context, req model.CreateUserRequest) (*model.User, error) {
	query := `
		INSERT INTO users (username, email, bio)
		VALUES ($1, $2, $3)
		RETURNING id, username, email, bio, created_at, updated_at`

	user := &model.User{}
	err := r.db.QueryRowContext(ctx, query, req.Username, req.Email, req.Bio).Scan(
		&user.ID, &user.Username, &user.Email, &user.Bio,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("repository.Create: %w", err)
	}
	return user, nil
}

// GetByID retrieves a single user by UUID. Returns sql.ErrNoRows when the
// user does not exist — the handler layer translates that into a 404.
func (r *UserRepository) GetByID(ctx context.Context, id string) (*model.User, error) {
	query := `
		SELECT id, username, email, bio, created_at, updated_at
		FROM users
		WHERE id = $1`

	user := &model.User{}
	err := r.db.QueryRowContext(ctx, query, id).Scan(
		&user.ID, &user.Username, &user.Email, &user.Bio,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("repository.GetByID: %w", err)
	}
	return user, nil
}

// List returns a paginated slice of users ordered by creation time (newest first).
// limit and offset are clamped/validated by the handler before reaching here.
func (r *UserRepository) List(ctx context.Context, limit, offset int) ([]model.User, error) {
	query := `
		SELECT id, username, email, bio, created_at, updated_at
		FROM users
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2`

	rows, err := r.db.QueryContext(ctx, query, limit, offset)
	if err != nil {
		return nil, fmt.Errorf("repository.List: %w", err)
	}
	defer rows.Close()

	var users []model.User
	for rows.Next() {
		var u model.User
		if err := rows.Scan(&u.ID, &u.Username, &u.Email, &u.Bio, &u.CreatedAt, &u.UpdatedAt); err != nil {
			return nil, fmt.Errorf("repository.List scan: %w", err)
		}
		users = append(users, u)
	}
	// rows.Err() catches errors that occurred during iteration (e.g. network)
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("repository.List rows: %w", err)
	}

	// Return empty slice instead of nil so JSON serializes as [] not null
	if users == nil {
		users = []model.User{}
	}
	return users, nil
}

// Update applies a partial update to an existing user. It dynamically builds
// the SET clause from only the non-nil fields in the request, so unchanged
// fields are never touched. Returns the updated user or sql.ErrNoRows if
// the ID does not exist.
func (r *UserRepository) Update(ctx context.Context, id string, req model.UpdateUserRequest) (*model.User, error) {
	// Build SET clause dynamically from non-nil fields
	setClauses := []string{}
	args := []interface{}{}
	argIdx := 1 // PostgreSQL parameterized query index ($1, $2, ...)

	if req.Username != nil {
		setClauses = append(setClauses, fmt.Sprintf("username = $%d", argIdx))
		args = append(args, *req.Username)
		argIdx++
	}
	if req.Email != nil {
		setClauses = append(setClauses, fmt.Sprintf("email = $%d", argIdx))
		args = append(args, *req.Email)
		argIdx++
	}
	if req.Bio != nil {
		setClauses = append(setClauses, fmt.Sprintf("bio = $%d", argIdx))
		args = append(args, *req.Bio)
		argIdx++
	}

	// Nothing to update — just fetch and return the current state
	if len(setClauses) == 0 {
		return r.GetByID(ctx, id)
	}

	// Always bump updated_at on any mutation
	setClauses = append(setClauses, "updated_at = NOW()")

	query := fmt.Sprintf(`
		UPDATE users
		SET %s
		WHERE id = $%d
		RETURNING id, username, email, bio, created_at, updated_at`,
		strings.Join(setClauses, ", "), argIdx)

	args = append(args, id)

	user := &model.User{}
	err := r.db.QueryRowContext(ctx, query, args...).Scan(
		&user.ID, &user.Username, &user.Email, &user.Bio,
		&user.CreatedAt, &user.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("repository.Update: %w", err)
	}
	return user, nil
}

// Delete removes a user by ID. Returns sql.ErrNoRows when the user does
// not exist (the handler translates that into 404).
func (r *UserRepository) Delete(ctx context.Context, id string) error {
	query := `DELETE FROM users WHERE id = $1`

	result, err := r.db.ExecContext(ctx, query, id)
	if err != nil {
		return fmt.Errorf("repository.Delete: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("repository.Delete rows affected: %w", err)
	}
	if rowsAffected == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// Ping verifies database connectivity — used by the health check endpoint.
func (r *UserRepository) Ping(ctx context.Context) error {
	return r.db.PingContext(ctx)
}
