apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - shared/secrets.yaml
  - shared/configmap.yaml
  - postgres.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - redis/pvc.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - post-service/deployment.yaml
  - post-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - shared/gateway.yaml
  - shared/httproute.yaml
  - shared/gatewayclass.yaml
  - user-service/hpa.yaml
  - post-service/hpa.yaml
  - notification-service/hpa.yaml
  - policies/redis-policy.yaml
  - policies/api-policy.yaml
