apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-pod
          image: kamalv007/social-user-service:v1
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pulse-secrets
                  key: user-service-database-url
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: pulse-shared-config
                  key: LOG_LEVEL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
