"""
Post endpoints — the core of the Post Service.

All routes live under /api/v1 and return the uniform APIResponse envelope:
    { "data": <payload | null>, "error": <message | null> }

UUID generation for new posts is delegated to PostgreSQL
(gen_random_uuid()) so Python never has to produce IDs.
"""

import asyncio
import logging
from typing import Optional

from fastapi import APIRouter, Query, Request, Response, status

from app.schemas import APIResponse, CreatePostRequest, PostResponse

logger = logging.getLogger("post-service")

router = APIRouter(prefix="/api/v1", tags=["posts"])


# ------------------------------------------------------------------
# Helpers — access shared resources stored on the FastAPI app instance
# ------------------------------------------------------------------


def _db(request: Request):
    """Convenience accessor for the Database singleton."""
    return request.app.state.db


def _user_client(request: Request):
    """Convenience accessor for the UserServiceClient singleton."""
    return request.app.state.user_client


def _event_publisher(request: Request):
    """Convenience accessor for the EventPublisher singleton."""
    return request.app.state.event_publisher


# ------------------------------------------------------------------
# POST /posts — Create a new post
# ------------------------------------------------------------------


@router.post("/posts", status_code=status.HTTP_201_CREATED, response_model=APIResponse)
async def create_post(body: CreatePostRequest, request: Request):
    """Create a new post.

    Steps:
    1. Validate that the user exists (calls User Service).
    2. INSERT into PostgreSQL (UUID generated by gen_random_uuid()).
    3. Publish a `new_post` event to Redis.
    4. Return the created post.
    """
    user_id = str(body.user_id)

    # 1. Validate user via User Service
    user_exists = await _user_client(request).validate_user(user_id)
    if not user_exists:
        logger.info("Post creation rejected — user not found", extra={"user_id": user_id})
        return Response(
            content=APIResponse(data=None, error=f"User {user_id} not found").model_dump_json(),
            status_code=status.HTTP_400_BAD_REQUEST,
            media_type="application/json",
        )

    # 2. Insert post (psycopg2 is sync — run in threadpool)
    query = """
        INSERT INTO posts (user_id, content)
        VALUES (%s, %s)
        RETURNING id, user_id, content, created_at
    """
    row = await asyncio.to_thread(_db(request).fetchone, query, (user_id, body.content))

    # Convert to a plain serializable dict
    post = _row_to_dict(row)

    logger.info("Post created", extra={"post_id": post["id"], "user_id": user_id})

    # 3. Publish event (best-effort — don't fail the request if Redis is down)
    try:
        await _event_publisher(request).publish_new_post(post)
    except Exception as exc:
        logger.warning("Failed to publish new_post event: %s", str(exc))

    # 4. Return 201
    return APIResponse(data=PostResponse(**post).model_dump(mode="json"))


# ------------------------------------------------------------------
# GET /posts/{post_id} — Retrieve a single post
# ------------------------------------------------------------------


@router.get("/posts/{post_id}", response_model=APIResponse)
async def get_post(post_id: str, request: Request):
    """Fetch a single post by its UUID."""
    query = "SELECT id, user_id, content, created_at FROM posts WHERE id = %s"
    row = await asyncio.to_thread(_db(request).fetchone, query, (post_id,))

    if row is None:
        return Response(
            content=APIResponse(data=None, error="Post not found").model_dump_json(),
            status_code=status.HTTP_404_NOT_FOUND,
            media_type="application/json",
        )

    post = _row_to_dict(row)
    return APIResponse(data=PostResponse(**post).model_dump(mode="json"))


# ------------------------------------------------------------------
# GET /posts — List posts (with optional user_id filter + pagination)
# ------------------------------------------------------------------


@router.get("/posts", response_model=APIResponse)
async def list_posts(
    request: Request,
    user_id: Optional[str] = Query(None, description="Filter by author UUID"),
    limit: int = Query(20, ge=1, le=100, description="Max posts to return"),
    offset: int = Query(0, ge=0, description="Pagination offset"),
):
    """Return a paginated list of posts, optionally filtered by user_id."""
    if user_id:
        query = """
            SELECT id, user_id, content, created_at
            FROM posts
            WHERE user_id = %s
            ORDER BY created_at DESC
            LIMIT %s OFFSET %s
        """
        params = (user_id, limit, offset)
    else:
        query = """
            SELECT id, user_id, content, created_at
            FROM posts
            ORDER BY created_at DESC
            LIMIT %s OFFSET %s
        """
        params = (limit, offset)

    rows = await asyncio.to_thread(_db(request).fetchall, query, params)
    posts = [PostResponse(**_row_to_dict(r)).model_dump(mode="json") for r in rows]
    return APIResponse(data=posts)


# ------------------------------------------------------------------
# DELETE /posts/{post_id} — Delete a post
# ------------------------------------------------------------------


@router.delete("/posts/{post_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_post(post_id: str, request: Request):
    """Delete a post by UUID. Returns 204 on success, 404 if not found."""
    # Check existence first
    check_query = "SELECT id FROM posts WHERE id = %s"
    row = await asyncio.to_thread(_db(request).fetchone, check_query, (post_id,))

    if row is None:
        return Response(
            content=APIResponse(data=None, error="Post not found").model_dump_json(),
            status_code=status.HTTP_404_NOT_FOUND,
            media_type="application/json",
        )

    delete_query = "DELETE FROM posts WHERE id = %s"
    await asyncio.to_thread(_db(request).execute, delete_query, (post_id,))
    logger.info("Post deleted", extra={"post_id": post_id})

    # 204 No Content — empty body
    return Response(status_code=status.HTTP_204_NO_CONTENT)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------


def _row_to_dict(row) -> dict:
    """Convert a RealDictRow to a plain dict with string-safe values."""
    return {
        "id": str(row["id"]),
        "user_id": str(row["user_id"]),
        "content": row["content"],
        "created_at": row["created_at"].isoformat() if row["created_at"] else None,
    }
