apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          securityContext:
            runAsNonRoot: ture
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pulse-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pulse-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: "pulse"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "pulse"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "pulse"]
            initialDelaySeconds: 5
            periodSeconds: 5

      volumes:
        - name: init-db
          configMap:
            name: pulse-init-db
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
